# Site settings
author: Thor Summerall
title: Thor's School Blog
header-img: img/home-bg.png
email: thor.summerall@gmail.com
copyright_name: Thor Summerall
description: > # this means to ignore newlines until "baseurl:"
  Thor's Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ThorSummerall

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
